apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::050451372978:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-wuMHzikew1l8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::050451372978:user/yeguru
      username: yeguru
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-01T02:02:38Z"
  name: aws-auth
  namespace: kube-system
  uid: c43e275b-75c5-427f-abbc-eec378c10316